development:
  adapter: postgresql
  encoding: unicode
  database: uday_svm_development
  pool: 5
  username: uday_svm_user
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: uday_svm_test
  pool: 5
  username: uday_svm_user
  password: